title: Marko Djordjic # your name (or website title) here
logo: 
  "/images/portrait_photo.jpg?raw=true" # your photo (or logo) here
description: >
  Professional experience in object-oriented test-driven development of 
  ML models in production systems in Python. Industry experience in: 
  IOT, consumer analytics, and consulting. Typical use-cases according 
  to specific domains of application: implementation of LLMs for sales 
  analyses, corporate communications, summarization of large documents, 
  monitoring of equipment health from maintenance reports, prediction of 
  main bearing temperatures, indication of changes in the fuel oil types, 
  analyses of the overall health of the equipment, unsupervised anomaly 
  detection, etc.
 
linkedin:
  <a href="https://www.linkedin.com/in/markodjordjic/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
