title: Marko Djordjic # your name (or website title) here
logo: 
  "/images/portrait_photo.jpg?raw=true" # your photo (or logo) here
description: >
 
linkedin:
  <a href="https://www.linkedin.com/in/markodjordjic/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
