title: Marko Djordjic # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Extensive experience in object-oriented test-driven development of 
  ML models in production environment in Python, elementary experience 
  in ML model development in C++, and flexibility to adapt to new 
  languages. Industry experience in: IOT, consumer analytics, and 
  consulting<br><br>
  Time Series:
  Prediction of main bearing temperatures, turbo-charger temperature 
  trend analyses, indication of changes in the fuel oil types, 
  indication of the specific intervals of engine operation, 
  indication of replacement of parts, 
  analyses of the overall health of the equipment, 
  unsupervised anomaly detection, etc.
  NLP, LLM, and Text Analytics:
  Implementation of LLMs for sales analyses, implementation of LLMs for 
  corporate communications, development of methodologies for evaluation 
  of LLM performance, implementation of NLP methods assignment of 
  maintenance specifications, implementation of explainable AI methods 
  for text data, and similar AI technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here